In [1]:
import pandas as pd
import os

data_path = "../data/raw"

files = os.listdir(data_path)

print("Number of files:", len(files))

for file in files:
    print(file)

Number of files: 9
olist_customers_dataset.csv
olist_geolocation_dataset.csv
olist_orders_dataset.csv
olist_order_items_dataset.csv
olist_order_payments_dataset.csv
olist_order_reviews_dataset.csv
olist_products_dataset.csv
olist_sellers_dataset.csv
product_category_name_translation.csv

In [2]:
orders = pd.read_csv(
    "../data/raw/olist_orders_dataset.csv"
)

print("Rows:", len(orders))
print("Columns:", len(orders.columns))

orders.head()

Rows: 99441
Columns: 8

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [3]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [4]:
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [5]:
orders.duplicated().sum()

np.int64(0)

In [6]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [7]:
orders["order_status"].value_counts(normalize=True) * 100

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

In [8]:
orders.groupby("order_status")[
    [
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
].apply(lambda x: x.isnull().sum())

,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
order_status,,,
approved,0,2,2
canceled,141,550,619
created,5,5,5
delivered,14,2,8
invoiced,0,314,314
processing,0,301,301
shipped,0,0,1107
unavailable,0,609,609

In [9]:
delivered_missing = orders[
    (orders["order_status"] == "delivered") &
    (
        orders[
            [
                "order_approved_at",
                "order_delivered_carrier_date",
                "order_delivered_customer_date"
            ]
        ].isnull().any(axis=1)
    )
]

delivered_missing

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
5323,e04abd8149ef81b95221e88f6ed9ab6a,2127dc6603ac33544953ef05ec155771,delivered,2017-02-18 14:40:00,NaN,2017-02-23 12:04:47,2017-03-01 13:25:33,2017-03-17 00:00:00
16567,8a9adc69528e1001fc68dd0aaebbb54a,4c1ccc74e00993733742a3c786dc3c1f,delivered,2017-02-18 12:45:31,NaN,2017-02-23 09:01:52,2017-03-02 10:05:06,2017-03-21 00:00:00
19031,7013bcfc1c97fe719a7b5e05e61c12db,2941af76d38100e0f8740a374f1a5dc3,delivered,2017-02-18 13:29:47,NaN,2017-02-22 16:25:25,2017-03-01 08:07:38,2017-03-17 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
22663,5cf925b116421afa85ee25e99b4c34fb,29c35fc91fc13fb5073c8f30505d860d,delivered,2017-02-18 16:48:35,NaN,2017-02-22 11:23:10,2017-03-09 07:28:47,2017-03-31 00:00:00
23156,12a95a3c06dbaec84bcfb0e2da5d228a,1e101e0daffaddce8159d25a8e53f2b2,delivered,2017-02-17 13:05:55,NaN,2017-02-22 11:23:11,2017-03-02 11:09:19,2017-03-20 00:00:00
26800,c1d4211b3dae76144deccd6c74144a88,684cb238dc5b5d6366244e0e0776b450,delivered,2017-01-19 12:48:08,NaN,2017-01-25 14:56:50,2017-01-30 18:16:01,2017-03-01 00:00:00
38290,d69e5d356402adc8cf17e08b5033acfb,68d081753ad4fe22fc4d410a9eb1ca01,delivered,2017-02-19 01:28:47,NaN,2017-02-23 03:11:48,2017-03-02 03:41:58,2017-03-27 00:00:00
39334,d77031d6a3c8a52f019764e68f211c69,0bf35cac6cc7327065da879e2d90fae8,delivered,2017-02-18 11:04:19,NaN,2017-02-23 07:23:36,2017-03-02 16:15:23,2017-03-22 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
48401,7002a78c79c519ac54022d4f8a65e6e8,d5de688c321096d15508faae67a27051,delivered,2017-01-19 22:26:59,NaN,2017-01-27 11:08:05,2017-02-06 14:22:19,2017-03-16 00:00:00
61743,2eecb0d85f281280f79fa00f9cec1a95,a3d3c38e58b9d2dfb9207cab690b6310,delivered,2017-02-17 17:21:55,NaN,2017-02-22 11:42:51,2017-03-03 12:16:03,2017-03-20 00:00:00
63052,51eb2eebd5d76a24625b31c33dd41449,07a2a7e0f63fd8cb757ed77d4245623c,delivered,2017-02-18 15:52:27,NaN,2017-02-23 03:09:14,2017-03-07 13:57:47,2017-03-29 00:00:00
67697,88083e8f64d95b932164187484d90212,f67cd1a215aae2a1074638bbd35a223a,delivered,2017-02-18 22:49:19,NaN,2017-02-22 11:31:06,2017-03-02 12:06:06,2017-03-21 00:00:00
72407,3c0b8706b065f9919d0505d3b3343881,d85919cb3c0529589c6fa617f5f43281,delivered,2017-02-17 15:53:27,NaN,2017-02-22 11:31:30,2017-03-03 11:47:47,2017-03-23 00:00:00
73222,2aa91108853cecb43c84a5dc5b277475,afeb16c7f46396c0ed54acb45ccaaa40,delivered,2017-09-29 08:52:58,2017-09-29 09:07:16,NaN,2017-11-20 19:44:47,2017-11-14 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
84999,2babbb4b15e6d2dfe95e2de765c97bce,74bebaf46603f9340e3b50c6b086f992,delivered,2017-02-18 17:15:03,NaN,2017-02-22 11:23:11,2017-03-03 18:43:43,2017-03-31 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

In [ ]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [10]:
delivered_missing[
    [
        "order_id",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
]

,order_id,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN
5323,e04abd8149ef81b95221e88f6ed9ab6a,NaN,2017-02-23 12:04:47,2017-03-01 13:25:33
16567,8a9adc69528e1001fc68dd0aaebbb54a,NaN,2017-02-23 09:01:52,2017-03-02 10:05:06
19031,7013bcfc1c97fe719a7b5e05e61c12db,NaN,2017-02-22 16:25:25,2017-03-01 08:07:38
20618,f5dd62b788049ad9fc0526e3ad11a097,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN
22663,5cf925b116421afa85ee25e99b4c34fb,NaN,2017-02-22 11:23:10,2017-03-09 07:28:47
23156,12a95a3c06dbaec84bcfb0e2da5d228a,NaN,2017-02-22 11:23:11,2017-03-02 11:09:19
26800,c1d4211b3dae76144deccd6c74144a88,NaN,2017-01-25 14:56:50,2017-01-30 18:16:01
38290,d69e5d356402adc8cf17e08b5033acfb,NaN,2017-02-23 03:11:48,2017-03-02 03:41:58
39334,d77031d6a3c8a52f019764e68f211c69,NaN,2017-02-23 07:23:36,2017-03-02 16:15:23
43834,2ebdfc4f15f23b91474edf87475f108e,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN
48401,7002a78c79c519ac54022d4f8a65e6e8,NaN,2017-01-27 11:08:05,2017-02-06 14:22:19
61743,2eecb0d85f281280f79fa00f9cec1a95,NaN,2017-02-22 11:42:51,2017-03-03 12:16:03
63052,51eb2eebd5d76a24625b31c33dd41449,NaN,2017-02-23 03:09:14,2017-03-07 13:57:47
67697,88083e8f64d95b932164187484d90212,NaN,2017-02-22 11:31:06,2017-03-02 12:06:06
72407,3c0b8706b065f9919d0505d3b3343881,NaN,2017-02-22 11:31:30,2017-03-03 11:47:47
73222,2aa91108853cecb43c84a5dc5b277475,2017-09-29 09:07:16,NaN,2017-11-20 19:44:47
79263,e69f75a717d64fc5ecdfae42b2e8e086,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN
82868,0d3268bad9b086af767785e3f0fc0133,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN
84999,2babbb4b15e6d2dfe95e2de765c97bce,NaN,2017-02-22 11:23:11,2017-03-03 18:43:43
92643,2d858f451373b04fb5c984a1cc2defaf,2017-05-25 23:30:16,NaN,NaN
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN
98038,20edc82cf5400ce95e1afacc25798b31,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN

In [11]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

orders[date_columns] = orders[date_columns].apply(
    pd.to_datetime,
    errors="coerce"
)

In [12]:
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  datetime64[us]
 4   order_approved_at              99281 non-null  datetime64[us]
 5   order_delivered_carrier_date   97658 non-null  datetime64[us]
 6   order_delivered_customer_date  96476 non-null  datetime64[us]
 7   order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), str(3)
memory usage: 6.1 MB

In [13]:
orders[date_columns].isnull().sum()

order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [15]:
for name in files:
    df = pd.read_csv(data_path + "/" + name)
    print(f"\n{name.upper()}")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Columns:", list(df.columns))

OLIST_CUSTOMERS_DATASET.CSV
Rows: 99441
Columns: 5
Columns: ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

OLIST_GEOLOCATION_DATASET.CSV
Rows: 1000163
Columns: 5
Columns: ['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

OLIST_ORDERS_DATASET.CSV
Rows: 99441
Columns: 8
Columns: ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

OLIST_ORDER_ITEMS_DATASET.CSV
Rows: 112650
Columns: 7
Columns: ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

OLIST_ORDER_PAYMENTS_DATASET.CSV
Rows: 103886
Columns: 5
Columns: ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

OLIST_ORDER_REVIEWS_DATASET.CSV
Rows: 99224
Columns: 7
Columns: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

OLIST_PRODUCTS_DATASET.CSV
Rows: 32951
Columns: 9
Columns: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

OLIST_SELLERS_DATASET.CSV
Rows: 3095
Columns: 4
Columns: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

PRODUCT_CATEGORY_NAME_TRANSLATION.CSV
Rows: 71
Columns: 2
Columns: ['product_category_name', 'product_category_name_english']

In [16]:
for name, path in {
    "reviews": "../data/raw/olist_order_reviews_dataset.csv",
    "products": "../data/raw/olist_products_dataset.csv",
    "sellers": "../data/raw/olist_sellers_dataset.csv"
}.items():
    df = pd.read_csv(path)
    print(f"\n{name.upper()}")
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("Columns:", list(df.columns))

REVIEWS
Rows: 99224
Columns: 7
Columns: ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

PRODUCTS
Rows: 32951
Columns: 9
Columns: ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

SELLERS
Rows: 3095
Columns: 4
Columns: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

In [17]:
tables = {
    "customers": "../data/raw/olist_customers_dataset.csv",
    "geolocation": "../data/raw/olist_geolocation_dataset.csv",
    "order_items": "../data/raw/olist_order_items_dataset.csv",
    "order_payments": "../data/raw/olist_order_payments_dataset.csv",
    "order_reviews": "../data/raw/olist_order_reviews_dataset.csv",
    "orders": "../data/raw/olist_orders_dataset.csv",
    "products": "../data/raw/olist_products_dataset.csv",
    "sellers": "../data/raw/olist_sellers_dataset.csv",
    "category_translation": "../data/raw/product_category_name_translation.csv"
}

for name, path in tables.items():
    df = pd.read_csv(path)
    print(f"{name}: {df.duplicated().sum()} exact duplicate rows")

customers: 0 exact duplicate rows
geolocation: 261831 exact duplicate rows
order_items: 0 exact duplicate rows
order_payments: 0 exact duplicate rows
order_reviews: 0 exact duplicate rows
orders: 0 exact duplicate rows
products: 0 exact duplicate rows
sellers: 0 exact duplicate rows
category_translation: 0 exact duplicate rows

In [18]:
geo = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")

print("Total rows:", len(geo))
print("Exact duplicate rows:", geo.duplicated().sum())
print("Rows after removing exact duplicates:", len(geo.drop_duplicates()))

Total rows: 1000163
Exact duplicate rows: 261831
Rows after removing exact duplicates: 738332

In [19]:
geo_unique = geo.drop_duplicates()

print("Unique ZIP code prefixes:", geo_unique["geolocation_zip_code_prefix"].nunique())
print("Total rows:", len(geo_unique))

Unique ZIP code prefixes: 19015
Total rows: 738332

In [20]:
geo_cleaned = geo.drop_duplicates().copy()

print("Original rows:", len(geo))
print("Cleaned rows:", len(geo_cleaned))
print("Removed duplicates:", len(geo) - len(geo_cleaned))

Original rows: 1000163
Cleaned rows: 738332
Removed duplicates: 261831

In [21]:
print("Remaining exact duplicates:", geo_cleaned.duplicated().sum())

Remaining exact duplicates: 0

In [22]:
for name, path in tables.items():
    df = pd.read_csv(path)

    missing = df.isnull().sum()
    missing = missing[missing > 0]

    print(f"\n{name.upper()}")
    
    if len(missing) == 0:
        print("No missing values")
    else:
        print(missing)

CUSTOMERS
No missing values

GEOLOCATION
No missing values

ORDER_ITEMS
No missing values

ORDER_PAYMENTS
No missing values

ORDER_REVIEWS
review_comment_title      87656
review_comment_message    58247
dtype: int64

ORDERS
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

PRODUCTS
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

SELLERS
No missing values

CATEGORY_TRANSLATION
No missing values

In [23]:
reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

print("Total reviews:", len(reviews))
print("\nMissing comment title:", reviews["review_comment_title"].isnull().sum())
print("Missing comment message:", reviews["review_comment_message"].isnull().sum())

print("\nReview score distribution:")
print(reviews["review_score"].value_counts().sort_index())

Total reviews: 99224

Missing comment title: 87656
Missing comment message: 58247

Review score distribution:
review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [24]:
checks = {
    "order_items": "../data/raw/olist_order_items_dataset.csv",
    "order_payments": "../data/raw/olist_order_payments_dataset.csv",
    "order_reviews": "../data/raw/olist_order_reviews_dataset.csv",
    "products": "../data/raw/olist_products_dataset.csv"
}

for name, path in checks.items():
    df = pd.read_csv(path)

    print(f"\n{name.upper()}")
    print(df.dtypes)

ORDER_ITEMS
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

ORDER_PAYMENTS
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

ORDER_REVIEWS
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

PRODUCTS
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [25]:
items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")
payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")
reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")
products = pd.read_csv("../data/raw/olist_products_dataset.csv")

print("ORDER ITEMS")
print("Price <= 0:", (items["price"] <= 0).sum())
print("Freight <= 0:", (items["freight_value"] <= 0).sum())

print("\nPAYMENTS")
print("Payment value <= 0:", (payments["payment_value"] <= 0).sum())
print("Installments <= 0:", (payments["payment_installments"] <= 0).sum())

print("\nREVIEWS")
print("Review score outside 1-5:",
      ((reviews["review_score"] < 1) | (reviews["review_score"] > 5)).sum())

print("\nPRODUCTS")
print("Weight <= 0:", (products["product_weight_g"] <= 0).sum())
print("Length <= 0:", (products["product_length_cm"] <= 0).sum())
print("Height <= 0:", (products["product_height_cm"] <= 0).sum())
print("Width <= 0:", (products["product_width_cm"] <= 0).sum())

ORDER ITEMS
Price <= 0: 0
Freight <= 0: 383

PAYMENTS
Payment value <= 0: 9
Installments <= 0: 2

REVIEWS
Review score outside 1-5: 0

PRODUCTS
Weight <= 0: 4
Length <= 0: 0
Height <= 0: 0
Width <= 0: 0

In [26]:
print("FREIGHT <= 0")
print(items.loc[items["freight_value"] <= 0,
                ["order_id", "order_item_id", "price", "freight_value"]].head(20))

print("\nPAYMENT VALUE <= 0")
print(payments.loc[payments["payment_value"] <= 0,
                    ["order_id", "payment_type", "payment_installments", "payment_value"]])

print("\nPAYMENT INSTALLMENTS <= 0")
print(payments.loc[payments["payment_installments"] <= 0,
                    ["order_id", "payment_type", "payment_installments", "payment_value"]])

print("\nPRODUCT WEIGHT <= 0")
print(products.loc[products["product_weight_g"] <= 0,
                    ["product_id", "product_category_name", "product_weight_g"]])

FREIGHT <= 0
                              order_id  order_item_id  price  freight_value
114   00404fa7a687c8c44ca69d42695aae73              1   99.9            0.0
258   00a870c6c06346e85335524935c600c0              1   69.9            0.0
483   011c899816ea29773525bd3322dbb6aa              1   99.9            0.0
508   012b3f6ab7776a8ab3443a4ad7bef2e6              1   53.9            0.0
509   012b3f6ab7776a8ab3443a4ad7bef2e6              2   53.9            0.0
1784  04105b54650921ca3246f52e6f175f46              1   69.9            0.0
2232  0517a3e68dac3308995edca2144db36e              1   99.9            0.0
2714  061ba2e2d7544790b6ed6b5b4dd9278c              1  110.0            0.0
3224  07441f525824bc6b31d4dc19c5d49fc9              1  106.9            0.0
3378  079f16689c29acb6cab92978e6af2137              1   69.9            0.0
3648  0849ccbfff0e8fd7168be6a62ca74a0d              1   99.9            0.0
3878  08c3d8da1ee7ffc88a41cd145a4675ba              1   69.9            0.0
4464  0a0e91f265e0c09af322a473351b61d1              1  106.9            0.0
4465  0a0eb4fdd818ed6fb62d07792c948971              1  116.9            0.0
4510  0a2f51f07c7b99722f843490cd20ec09              1   69.9            0.0
4743  0ab73486735f114f9e844522fa9b16ec              1   99.9            0.0
4941  0b2d6210fb2a3be6f54add89639740ab              1   53.9            0.0
5228  0bde6dfc382fc35f1a5ebf8ddf8e639d              1   99.9            0.0
5507  0c7207c23f4eb8c3b374c9b6f11d75b7              1  117.9            0.0
5608  0ca64e59f59b26fb6fb2726f907bb52d              1   99.9            0.0

PAYMENT VALUE <= 0
                                order_id payment_type  payment_installments  \
19922   8bcbe01d44d147f901cd3192671144db      voucher                     1
36822   fa65dad1b0e818e3ccc5cb0e39231352      voucher                     1
43744   6ccb433e00daae1283ccc956189c82ae      voucher                     1
51280   4637ca194b6387e2d538dc89b124b0ee  not_defined                     1
57411   00b1cb0320190ca0daa2c88b35206009  not_defined                     1
62674   45ed6e85398a87c253db47c2d9f48216      voucher                     1
77885   fa65dad1b0e818e3ccc5cb0e39231352      voucher                     1
94427   c8c528189310eaa44a745b8d9d26908b  not_defined                     1
100766  b23878b3e8eb4d25a158f57d96331b18      voucher                     1

        payment_value
19922             0.0
36822             0.0
43744             0.0
51280             0.0
57411             0.0
62674             0.0
77885             0.0
94427             0.0
100766            0.0

PAYMENT INSTALLMENTS <= 0
                               order_id payment_type  payment_installments  \
46982  744bade1fcf9ff3f31d860ace076d422  credit_card                     0
79014  1a57108394169c0b47d8f876acc9ba2d  credit_card                     0

       payment_value
46982          58.69
79014         129.94

PRODUCT WEIGHT <= 0
                             product_id product_category_name  \
9769   81781c0fed9fe1ad6e8c81fca1e1cb08       cama_mesa_banho
13683  8038040ee2a71048d4bdbbdc985b69ab       cama_mesa_banho
14997  36ba42dd187055e1fbe943b2d11430ca       cama_mesa_banho
32079  e673e90efa65a5409ff4196c038bb5af       cama_mesa_banho

       product_weight_g
9769                0.0
13683               0.0
14997               0.0
32079               0.0

In [27]:
print(payments.loc[payments["payment_value"] <= 0,
                   ["order_id", "payment_type",
                    "payment_installments", "payment_value"]].to_string(index=False))

                        order_id payment_type  payment_installments  payment_value
8bcbe01d44d147f901cd3192671144db      voucher                     1            0.0
fa65dad1b0e818e3ccc5cb0e39231352      voucher                     1            0.0
6ccb433e00daae1283ccc956189c82ae      voucher                     1            0.0
4637ca194b6387e2d538dc89b124b0ee  not_defined                     1            0.0
00b1cb0320190ca0daa2c88b35206009  not_defined                     1            0.0
45ed6e85398a87c253db47c2d9f48216      voucher                     1            0.0
fa65dad1b0e818e3ccc5cb0e39231352      voucher                     1            0.0
c8c528189310eaa44a745b8d9d26908b  not_defined                     1            0.0
b23878b3e8eb4d25a158f57d96331b18      voucher                     1            0.0

In [28]:
print(payments.loc[payments["payment_installments"] <= 0,
                   ["order_id", "payment_type",
                    "payment_installments", "payment_value"]].to_string(index=False))

                        order_id payment_type  payment_installments  payment_value
744bade1fcf9ff3f31d860ace076d422  credit_card                     0          58.69
1a57108394169c0b47d8f876acc9ba2d  credit_card                     0         129.94

In [29]:
print(
    payments.loc[
        payments["payment_value"] <= 0,
        ["order_id", "payment_type", "payment_installments", "payment_value"]
    ].to_string(index=False)
)

                        order_id payment_type  payment_installments  payment_value
8bcbe01d44d147f901cd3192671144db      voucher                     1            0.0
fa65dad1b0e818e3ccc5cb0e39231352      voucher                     1            0.0
6ccb433e00daae1283ccc956189c82ae      voucher                     1            0.0
4637ca194b6387e2d538dc89b124b0ee  not_defined                     1            0.0
00b1cb0320190ca0daa2c88b35206009  not_defined                     1            0.0
45ed6e85398a87c253db47c2d9f48216      voucher                     1            0.0
fa65dad1b0e818e3ccc5cb0e39231352      voucher                     1            0.0
c8c528189310eaa44a745b8d9d26908b  not_defined                     1            0.0
b23878b3e8eb4d25a158f57d96331b18      voucher                     1            0.0

In [30]:
print(
    products.loc[
        products["product_weight_g"] <= 0,
        [
            "product_id",
            "product_category_name",
            "product_weight_g",
            "product_length_cm",
            "product_height_cm",
            "product_width_cm"
        ]
    ].to_string(index=False)
)

                      product_id product_category_name  product_weight_g  product_length_cm  product_height_cm  product_width_cm
81781c0fed9fe1ad6e8c81fca1e1cb08       cama_mesa_banho               0.0               30.0               25.0              30.0
8038040ee2a71048d4bdbbdc985b69ab       cama_mesa_banho               0.0               30.0               25.0              30.0
36ba42dd187055e1fbe943b2d11430ca       cama_mesa_banho               0.0               30.0               25.0              30.0
e673e90efa65a5409ff4196c038bb5af       cama_mesa_banho               0.0               30.0               25.0              30.0

In [31]:
items["shipping_limit_date"] = pd.to_datetime(
    items["shipping_limit_date"],
    errors="coerce"
)

reviews["review_creation_date"] = pd.to_datetime(
    reviews["review_creation_date"],
    errors="coerce"
)

reviews["review_answer_timestamp"] = pd.to_datetime(
    reviews["review_answer_timestamp"],
    errors="coerce"
)

print(items["shipping_limit_date"].dtype)
print(reviews["review_creation_date"].dtype)
print(reviews["review_answer_timestamp"].dtype)

datetime64[us]
datetime64[us]
datetime64[us]

In [32]:
print("ORDER DATE ANOMALIES")

print(
    "Approved before purchase:",
    (orders["order_approved_at"] < orders["order_purchase_timestamp"]).sum()
)

print(
    "Carrier before purchase:",
    (orders["order_delivered_carrier_date"] < orders["order_purchase_timestamp"]).sum()
)

print(
    "Customer delivery before purchase:",
    (orders["order_delivered_customer_date"] < orders["order_purchase_timestamp"]).sum()
)

print(
    "Customer delivery before carrier:",
    (
        orders["order_delivered_customer_date"]
        < orders["order_delivered_carrier_date"]
    ).sum()
)

print(
    "Estimated delivery before purchase:",
    (
        orders["order_estimated_delivery_date"]
        < orders["order_purchase_timestamp"]
    ).sum()
)

ORDER DATE ANOMALIES
Approved before purchase: 0
Carrier before purchase: 166
Customer delivery before purchase: 0
Customer delivery before carrier: 23
Estimated delivery before purchase: 0

In [33]:
carrier_anomalies = orders[
    orders["order_delivered_carrier_date"]
    < orders["order_purchase_timestamp"]
]

print(
    carrier_anomalies[
        [
            "order_id",
            "order_status",
            "order_purchase_timestamp",
            "order_approved_at",
            "order_delivered_carrier_date",
            "order_delivered_customer_date",
            "order_estimated_delivery_date"
        ]
    ].to_string(index=False)
)

                        order_id order_status order_purchase_timestamp   order_approved_at order_delivered_carrier_date order_delivered_customer_date order_estimated_delivery_date
b9afddbdcfadc9a87b41a83271c3e888    delivered      2018-08-16 13:50:48 2018-08-16 14:05:13          2018-08-16 13:27:00           2018-08-24 14:58:37                    2018-09-04
ad133696906f6a78826daa0911b7daec    delivered      2018-06-15 15:41:22 2018-06-15 16:19:23          2018-06-15 14:52:00           2018-06-22 18:09:37                    2018-07-18
74e033208dc13a7b8127eb8e73d09b76    delivered      2018-05-02 10:48:44 2018-05-02 11:13:45          2018-05-02 09:49:00           2018-05-07 23:06:36                    2018-05-29
a6b58794fd2ba533359a76c08df576e3    delivered      2018-05-14 15:18:23 2018-05-14 15:33:35          2018-05-14 13:46:00           2018-05-19 19:33:32                    2018-06-08
5792e0b1c8c8a2bf53af468c9a422c88    delivered      2018-07-26 13:25:14 2018-07-26 13:35:14          2018-07-26 12:42:00           2018-07-30 14:45:02                    2018-08-09
c3eb293fd154223498b6551a728203e8    delivered      2018-07-19 14:06:04 2018-07-19 14:22:51          2018-07-19 13:49:00           2018-07-24 19:35:36                    2018-08-06
b0c2a7d04b165525254254a728c50a4e    delivered      2018-06-07 13:28:30 2018-06-07 13:57:22          2018-06-07 13:22:00           2018-06-21 17:36:43                    2018-07-04
2033a4586b5bec3229ebc1675a8ae092    delivered      2018-06-12 10:10:25 2018-06-12 10:39:59          2018-06-12 10:09:00           2018-06-19 14:08:27                    2018-07-19
08adcddad19d3acf37d1fa01cb9ded1e    delivered      2018-06-27 11:16:44 2018-06-27 11:30:56          2018-06-27 10:57:00           2018-06-29 17:39:53                    2018-07-18
dee6298ce7d1fb2645141ef9972157aa      shipped      2018-04-30 14:06:12 2018-04-30 14:15:24          2018-04-30 12:59:00                           NaT                    2018-05-28
4e157a36ea9cf89bde6fff57a780b525    delivered      2018-08-24 14:37:50 2018-08-24 14:50:14          2018-08-24 12:43:00           2018-08-30 20:47:26                    2018-09-10
d454d6650d375ebc3f9667a4d2fe161c    delivered      2018-05-10 09:12:16 2018-05-10 09:35:13          2018-05-10 09:11:00           2018-05-11 18:58:28                    2018-05-23
a5a9f45d795fafe0077043697f62fd4f    delivered      2018-07-04 14:45:20 2018-07-05 16:30:50          2018-07-04 13:41:00           2018-07-11 23:08:32                    2018-08-01
dab23a46abb860b6b4816df41eacd610    delivered      2018-08-08 15:42:27 2018-08-08 15:55:11          2018-08-08 14:56:00           2018-08-11 17:04:47                    2018-08-17
b4180badf3ac49892e23d6e0276f1e84    delivered      2018-04-26 14:44:05 2018-04-26 14:55:14          2018-04-26 13:51:00           2018-05-03 00:14:44                    2018-06-06
6c5d1e03493316b72304f07834a03325    delivered      2018-06-12 13:56:41 2018-06-12 14:27:00          2018-06-12 13:06:00           2018-07-17 16:32:20                    2018-07-11
ede6a833580744e002b0ee65323a3006    delivered      2018-08-17 15:11:53 2018-08-17 15:29:26          2018-08-17 14:07:00           2018-08-22 19:28:52                    2018-09-12
1227f9af3b2ddb0b95060aab8e5b3dc7    delivered      2018-05-10 14:48:29 2018-05-10 15:11:25          2018-05-10 14:00:00           2018-05-18 16:21:53                    2018-06-07
2996234f359b5a3b99263b0f5b841d86    delivered      2018-08-15 15:48:50 2018-08-15 16:05:12          2018-08-15 14:16:00           2018-08-22 22:34:27                    2018-09-04
108c3238d247dead3fd7423cf8990c5b    delivered      2018-08-14 13:49:12 2018-08-14 14:04:33          2018-08-14 13:17:00           2018-08-23 16:06:36                    2018-09-06
0150004d4d8eb63f9948de164da34e34    delivered      2018-05-15 15:13:06 2018-05-15 15:34:59          2018-05-15 14:58:00           2018-05-23 18:13:16                    2018-06-07
da383ff6aa9558f3bd909b1d76789381    delivered      2018-08-20 13:56:52 2018-08-20 16:11:39          2018-08-20 13:55:00           2018-08-27 23:32:23                    2018-08-31
9b087af1d905d8987ae126797c9d15b1    delivered      2018-08-01 13:47:04 2018-08-01 14:04:26          2018-08-01 13:31:00           2018-08-08 13:35:29                    2018-08-15
fb3cf8c9eb2412b0edc0a00a8f43a869    delivered      2018-05-29 14:07:25 2018-05-29 14:39:27          2018-05-29 13:58:00           2018-06-05 21:46:32                    2018-07-20
0cf80be143500050973f324c3e068196    delivered      2018-07-26 14:33:26 2018-07-26 14:45:08          2018-07-26 13:32:00           2018-07-30 22:22:08                    2018-08-15
28fb57d39d543fade1e8fa4804f7483e    delivered      2018-06-07 14:47:17 2018-06-07 15:18:51          2018-06-07 14:09:00           2018-06-20 11:28:36                    2018-07-11
6192897f85cb2aff6dd1fca56fddb45e    delivered      2018-07-18 13:34:22 2018-07-18 13:50:12          2018-07-18 11:33:00           2018-07-26 15:02:53                    2018-08-03
c76b75e541b06461ec9cf363fd962ee3    delivered      2018-05-23 15:50:05 2018-05-23 16:16:01          2018-05-23 14:51:00           2018-06-07 19:31:51                    2018-07-02
d19e65e88e48b013c91b0e77c852d06e    delivered      2018-06-08 16:40:18 2018-06-08 19:31:01          2018-06-08 15:31:00           2018-06-23 18:28:47                    2018-07-18
e1bea0700731c9179b4e7e2e0183aa14    delivered      2018-08-03 15:37:48 2018-08-03 15:55:20          2018-08-03 15:09:00           2018-08-08 20:28:35                    2018-08-15
a103ca0d5926c0afb6a2892545f93a7c    delivered      2018-05-16 14:37:16 2018-05-16 15:18:06          2018-05-16 14:05:00           2018-06-02 17:27:55                    2018-06-07
a14cb0a59ebadf133edc5ccb9ccfc0e7    delivered      2018-06-26 15:38:05 2018-06-26 15:56:48          2018-06-26 15:18:00           2018-06-28 21:38:33                    2018-07-12
33526a04c7941ab386cc410962b171a0    delivered      2018-07-24 13:43:20 2018-07-24 13:55:23          2018-07-24 13:03:00           2018-07-30 12:26:29                    2018-08-17
31baa0ae964c43e70c451e1928483669    delivered      2018-08-23 10:13:22 2018-08-23 10:25:32          2018-08-23 08:54:00           2018-08-25 12:28:46                    2018-09-13
fcb9ec0e86e6d326a21a96c2008c8610    delivered      2018-08-16 16:28:13 2018-08-16 16:49:04          2018-08-16 16:27:00           2018-08-20 19:54:47                    2018-09-03
5b9075f2428968c2587dad5024af0f63    delivered      2018-06-26 11:24:48 2018-06-26 11:35:59          2018-06-26 10:58:00           2018-07-12 14:37:43                    2018-07-25
1046a71a57b33b4a92f9f932237f1ab0    delivered      2018-07-31 13:56:17 2018-07-31 14:05:11          2018-07-31 12:57:00           2018-08-03 17:12:13                    2018-08-17
1388e91d7d43769d6bd71f89a48a2929    delivered      2018-06-18 14:04:50 2018-06-18 14:19:43          2018-06-18 12:22:00           2018-06-25 22:08:40                    2018-07-16
f2a150c813c1eb96fd1883c1ed8fd9e5    delivered      2018-06-19 10:14:30 2018-06-19 10:37:37          2018-06-19 10:14:00           2018-06-27 17:04:42                    2018-07-24
2ea06e4e577c7be86e2e35ab0d7e74b8    delivered      2018-05-09 13:14:53 2018-05-09 13:35:00          2018-05-09 12:52:00           2018-05-15 15:38:51                    2018-05-28
e23c9dcc304042fa90d538be679fa68d    delivered      2018-06-13 11:41:23 2018-06-13 13:31:40          2018-06-13 09:53:00           2018-06-25 13:57:31                    2018-07-11
9dafdbeb6a7b7240bc32fd6861c42f54    delivered      2018-06-07 13:02:12 2018-06-07 13:18:07          2018-06-07 12:02:00           2018-06-13 23:12:06                    2018-07-05
e300c76076c4b56031abe6f3ff54817f    delivered      2018-08-15 10:59:22 2018-08-15 11:24:10          2018-08-15 10:27:00           2018-08-21 17:21:15                    2018-08-29
e0017093576ff7e25777c2d023eb1cd9    delivered      2018-06-26 14:57:28 2018-06-26 15:16:21          2018-06-26 14:50:00           2018-06-28 21:48:51                    2018-08-01
154029fef0e3e2f72ef09775cc9d1af1    delivered      2018-05-22 11:29:21 2018-05-22 11:53:51          2018-05-22 10:46:00           2018-06-07 20:58:39                    2018-06-21
ab815320404ada153a9d06f166c961dc    delivered      2018-05-17 09:48:09 2018-05-17 10:38:29          2018-05-17 09:45:00           2018-05-30 21:12:35                    2018-06-13
800bb72be8df9c5372c6a4235d38de9b    delivered      2018-05-14 14:55:29 2018-05-14 15:17:28          2018-05-14 14:47:00           2018-05-20 16:08:26                    2018-05-30
7c48bb55e8e4f7e56d412e9653db37bc    delivered      2018-07-16 18:40:53 2018-07-16 18:50:22          2018-01-26 13:35:00           2018-07-23 20:04:45                    2018-08-07
ece7b7cba1247b9ac059fc6a6528a075    delivered      2018-05-15 15:17:06 2018-05-15 15:35:12          2018-05-15 15:05:00           2018-05-25 10:18:23                    2018-06-11
bb3164e0236b64b580d475215f1004d2    delivered      2018-06-19 15:12:47 2018-06-19 15:37:45          2018-06-19 13:58:00           2018-06-22 21:56:47                    2018-07-11
b39c24b97fedca1cb67932d9864957c6    delivered      2018-06-18 13:48:28 2018-06-18 14:19:16          2018-06-18 12:53:00           2018-07-03 16:46:44                    2018-07-12
b6ab1ce66f41dbbd8e998bfb0eab8bd5    delivered      2018-06-26 14:14:25 2018-06-26 14:34:15          2018-06-26 13:53:00           2018-06-30 18:18:32                    2018-07-31
4048feff4f2e6e394bcaf4981d27a9bd    delivered      2018-06-25 11:59:16 2018-06-25 12:13:40          2018-06-25 11:56:00           2018-06-26 20:45:42                    2018-07-05
55b653f93de6e994b6dda90f615c7a8f    delivered      2018-04-30 13:05:23 2018-04-30 13:15:21          2018-04-30 13:01:00           2018-05-04 18:03:43                    2018-05-21
995e90c3995e0f19a9579b90c6dcbad2    delivered      2018-07-04 14:52:16 2018-07-05 16:11:47          2018-07-04 14:51:00           2018-07-10 17:48:23                    2018-08-07
d5b8231ec694904371f3efcd3450ee94    delivered      2018-06-06 14:58:22 2018-06-06 15:13:46          2018-06-06 14:34:00           2018-06-14 01:38:35                    2018-07-17
42a212a14fd3e3b7e9c8245a00e35369    delivered      2018-07-26 13:37:11 2018-07-26 13:50:54          2018-07-26 12:52:00           2018-08-01 20:02:09                    2018-08-15
6f27ae84e8f6ee63438f59c04830b28a    delivered      2018-06-19 14:58:59 2018-06-19 15:19:48          2018-06-19 14:26:00           2018-07-05 23:42:22                    2018-07-16
fd58bdbb6cc5d7519e063c3ceb7e951b    delivered      2018-04-25 13:02:26 2018-04-25 13:15:26          2018-04-25 12:36:00           2018-05-08 16:32:17                    2018-05-28
0fa2c93bbfbce2c287bb56660c3998e3    delivered      2018-06-18 14:54:21 2018-06-18 15:17:12          2018-06-18 14:06:00           2018-06-28 18:41:14                    2018-07-25
8c8005895f46f6c1bdf16697c70e645a    delivered      2018-08-17 15:57:10 2018-08-17 16:10:14          2018-08-17 14:56:00           2018-08-25 16:08:37                    2018-09-19
ba6a0a51f6852a4e562acc5feb6ca75e    delivered      2018-06-12 14:14:08 2018-06-12 14:46:10          2018-06-12 13:50:00           2018-06-19 17:46:35                    2018-07-05
c3c86ecc0f7508ffce2a4662f49d9d8b    delivered      2018-05-14 12:42:52 2018-05-14 12:55:25          2018-05-14 12:25:00           2018-05-18 14:12:20                    2018-06-01
91be51c856a90d7efe86cf9d082d6ae3    delivered      2018-06-12 15:58:03 2018-06-12 16:32:26          2018-06-12 15:44:00           2018-06-15 15:42:07                    2018-07-12
ffcc17a2f3331d4d25cf692060921690    delivered      2018-06-29 14:41:28 2018-06-29 14:50:16          2018-06-29 14:40:00           2018-07-03 16:14:35                    2018-07-13
fe206005e41f89f9759ece7fe7acc9c3    delivered      2018-06-25 15:05:27 2018-06-25 15:18:59          2018-06-25 14:08:00           2018-07-03 20:10:15                    2018-07-23
819c0a8de9efdc8a6886525a06dc7967    delivered      2018-07-04 16:10:42 2018-07-05 16:21:06          2018-07-04 15:30:00           2018-07-12 15:08:34                    2018-07-26
9ac6f439f70af60a204c7d47285fa099    delivered      2018-08-16 15:46:02 2018-08-16 15:55:24          2018-08-16 14:20:00           2018-08-21 19:55:34                    2018-08-28
1d54af1bf3179b54f046212de28f8bc7    delivered      2018-08-09 08:37:26 2018-08-09 08:50:35          2018-08-09 08:33:00           2018-08-17 21:03:54                    2018-09-05
48300f948ed1d70ff6e5f733e30e5816    delivered      2018-06-21 14:37:50 2018-06-21 14:59:59          2018-06-21 13:09:00           2018-07-06 14:51:09                    2018-07-24
f0755c7d99a4a7f0bfa967f87d657855    delivered      2018-07-05 12:26:16 2018-07-05 16:32:14          2018-07-05 12:23:00           2018-07-13 21:27:50                    2018-08-02
eab659d04f2bba5abfe11a2e6ef92bd0    delivered      2018-06-05 13:24:11 2018-06-05 14:31:11          2018-06-05 12:34:00           2018-06-08 20:34:21                    2018-07-11
3ed559dec69ab96d9074fedaf18650eb    delivered      2018-06-15 13:20:09 2018-06-15 13:44:37          2018-06-15 11:22:00           2018-06-26 15:53:25                    2018-07-23
0474da9403011efc4abd2bf594e9b68b    delivered      2018-08-08 13:18:36 2018-08-08 13:30:15          2018-08-08 12:19:00           2018-08-13 22:10:52                    2018-08-29
1cb3c680ddf904752646028ee22073a4    delivered      2018-07-27 14:08:38 2018-07-27 14:24:04          2018-07-27 14:08:00           2018-08-02 18:56:47                    2018-08-07
9e85367165bb242141b1f2638d6fc239    delivered      2018-07-05 13:40:19 2018-07-05 16:31:55          2018-07-05 12:45:00           2018-07-12 23:12:12                    2018-08-03
6f09086a54ed13a7f152d6339e2ee5a3    delivered      2018-06-26 09:51:04 2018-06-26 10:18:00          2018-06-26 09:08:00           2018-06-28 16:32:10                    2018-07-20
dadc329b35c6c0dcbe7c3ddb1923f51a    delivered      2018-06-29 16:01:12 2018-06-29 16:11:43          2018-06-29 15:47:00           2018-07-05 20:54:44                    2018-07-31
cf5c8d9f52807cb2d2f0a0ff54c478da    delivered      2018-08-24 13:04:05 2018-08-24 13:24:27          2018-08-24 12:00:00           2018-08-30 19:11:50                    2018-10-05
0a84606bdb8331708400882d2e921524    delivered      2018-06-29 16:28:41 2018-06-29 16:51:20          2018-06-29 14:47:00           2018-07-03 14:44:33                    2018-07-17
1c958182f10d6fcbac7728c8d3a151f1    delivered      2018-07-23 15:09:44 2018-07-23 16:05:15          2018-07-23 14:52:00           2018-08-01 21:05:05                    2018-08-14
00d2559e61b9a0744a0552c35c5ecccb    delivered      2018-06-11 12:24:48 2018-06-11 13:32:18          2018-06-11 12:05:00           2018-06-18 16:51:52                    2018-06-28
8299066c13f491b4cf9bdb486d2058c2    delivered      2018-05-14 12:53:23 2018-05-14 13:17:03          2018-05-14 12:43:00           2018-05-23 21:21:54                    2018-06-06
1c723386781fca8d1e45ac747914962a    delivered      2018-08-06 15:47:47 2018-08-06 15:55:15          2018-08-06 15:06:00           2018-08-14 18:53:24                    2018-08-23
c45408df26d1ce2b64518a9a9d65fd04    delivered      2018-08-16 17:11:46 2018-08-16 17:29:05          2018-08-16 16:13:00           2018-08-22 14:33:43                    2018-09-05
e65f1eeee1f52024ad1dcd03447f7482    delivered      2018-05-18 15:03:19 2018-05-18 15:15:37          2018-05-18 15:00:00           2018-05-19 12:28:30                    2018-05-29
7ce4e38f4eadd993bb5b2e60bb7f7bec    delivered      2018-08-08 14:46:45 2018-08-08 15:05:01          2018-08-08 13:29:00           2018-08-15 18:55:45                    2018-08-28
69aca49c98f05af05bec6fa1f87a3059    delivered      2018-07-20 13:19:19 2018-07-20 13:30:13          2018-07-20 12:01:00           2018-07-25 17:03:35                    2018-08-14
7fb538147fab748faf726e6706589b74    delivered      2018-08-16 14:26:06 2018-08-16 15:24:46          2018-08-16 14:19:00           2018-08-21 19:14:28                    2018-09-03
44dd8e3e7650c35a1973a42498626ded    delivered      2018-07-13 15:08:43 2018-07-13 15:24:01          2018-07-13 14:36:00           2018-07-16 11:14:27                    2018-07-23
64ff09b60c2714ff11ebcf304ed21fb6    delivered      2018-07-31 14:04:37 2018-07-31 14:31:37          2018-07-31 13:34:00           2018-08-07 14:41:43                    2018-08-10
71fecd3061e596fd59e65e9d62886535    delivered      2018-05-08 14:17:52 2018-05-08 14:30:18          2018-05-08 13:43:00           2018-05-22 19:08:28                    2018-06-12
12052ac6aa067434388199224c0f11bc    delivered      2018-07-31 13:16:33 2018-07-31 13:25:25          2018-07-31 12:51:00           2018-08-09 21:15:51                    2018-08-28
60f7dee462ea29c73d75c9dcccf5d870    delivered      2018-06-15 07:32:22 2018-06-15 08:00:16          2018-06-15 07:00:00           2018-06-21 17:56:54                    2018-07-19
10251da35626072605d693e816f297ca    delivered      2018-08-13 15:27:36 2018-08-13 15:49:00          2018-08-13 14:45:00           2018-08-16 18:41:34                    2018-08-21
97d3870e43e40f4dcac70eec95a6b146    delivered      2018-08-10 12:23:32 2018-08-10 12:35:24          2018-08-10 12:11:00           2018-08-23 22:48:34                    2018-09-18
2d26e963bdb342dbdae1fad7ad2ea511    delivered      2018-08-14 12:35:00 2018-08-14 12:50:18          2018-08-14 12:23:00           2018-08-21 19:18:51                    2018-08-27
4381b4b79d51e72e0eb56a2fd1aea7b9    delivered      2018-05-18 14:39:06 2018-05-18 14:57:40          2018-05-18 13:51:00           2018-06-07 15:21:25                    2018-06-08
8b5512b2679b86761e6aadc28ed91762    delivered      2018-08-03 14:39:54 2018-08-03 14:50:14          2018-08-03 13:57:00           2018-08-22 18:03:43                    2018-10-01
bd47f29a1a6ede24f9dd4d5ca6027dd4    delivered      2018-07-16 15:34:37 2018-07-16 15:45:19          2018-07-16 14:29:00           2018-07-24 09:41:51                    2018-08-08
692f4207d359fbf24d641b1470721130    delivered      2018-06-04 12:10:06 2018-06-04 12:31:17          2018-06-04 11:04:00           2018-06-21 21:56:34                    2018-07-17
129b63bc323d7b5b2965a143b2e72cc7    delivered      2018-05-30 14:33:24 2018-05-30 14:57:24          2018-05-30 14:33:00           2018-06-08 13:58:41                    2018-07-05
c6f11a51ee3384a11e50cc55dc685c24    delivered      2018-08-15 14:02:44 2018-08-15 14:24:18          2018-08-15 13:56:00           2018-08-21 10:15:44                    2018-08-28
07f770114a6de1a65f865bf22d8bb20a    delivered      2018-08-06 09:17:53 2018-08-06 09:30:16          2018-08-06 08:44:00           2018-08-09 16:40:37                    2018-08-16
ed274ecbd297951203b23b1e071eb593    delivered      2018-05-15 15:33:44 2018-05-15 15:56:03          2018-05-15 14:13:00           2018-05-18 16:48:50                    2018-05-30
771e9bbd641d86a4ee75fe80bdf61d7b    delivered      2018-06-13 13:00:21 2018-06-13 13:17:05          2018-06-13 12:00:00           2018-06-21 22:56:45                    2018-07-17
70f814478ea3019fff8677f0aca6a54b    delivered      2018-08-23 15:58:16 2018-08-23 16:10:22          2018-08-23 15:31:00           2018-08-27 18:54:37                    2018-08-28
9711d975b961355b4b5d636857e48498    delivered      2018-06-13 15:23:50 2018-06-13 15:38:18          2018-06-13 13:15:00           2018-06-26 00:33:48                    2018-06-29
6c28cf68e8389e5024135b3d33d8a987    delivered      2018-05-09 12:23:00 2018-05-09 12:35:53          2018-05-09 11:09:00           2018-05-21 19:31:32                    2018-05-28
db090a16182b263b1e896bb26c6f66cf    delivered      2018-07-13 16:14:08 2018-07-13 16:44:09          2018-07-13 13:59:00           2018-07-27 11:34:31                    2018-08-06

In [34]:
print("Anomalies by order status:")
print(carrier_anomalies["order_status"].value_counts())

print("\nEarliest carrier timestamp:")
print(carrier_anomalies["order_delivered_carrier_date"].min())

print("\nEarliest purchase timestamp:")
print(carrier_anomalies["order_purchase_timestamp"].min())

Anomalies by order status:
order_status
delivered    165
shipped        1
Name: count, dtype: int64

Earliest carrier timestamp:
2018-01-26 13:35:00

Earliest purchase timestamp:
2018-04-25 13:02:26

In [35]:
print(
    carrier_anomalies[
        [
            "order_id",
            "order_status",
            "order_purchase_timestamp",
            "order_approved_at",
            "order_delivered_carrier_date"
        ]
    ].sort_values("order_purchase_timestamp").head(20).to_string(index=False)
)

                        order_id order_status order_purchase_timestamp   order_approved_at order_delivered_carrier_date
fd58bdbb6cc5d7519e063c3ceb7e951b    delivered      2018-04-25 13:02:26 2018-04-25 13:15:26          2018-04-25 12:36:00
b4180badf3ac49892e23d6e0276f1e84    delivered      2018-04-26 14:44:05 2018-04-26 14:55:14          2018-04-26 13:51:00
e4c540c341b9a50b1a1b28e71867eb5b    delivered      2018-04-26 15:55:42 2018-04-26 16:11:01          2018-04-26 14:55:00
9e6928e55ec6948338048d72ebdf2305    delivered      2018-04-27 15:12:36 2018-04-27 15:32:59          2018-04-27 15:08:00
5a339130640419f9e00ab4b6ff61dc22    delivered      2018-04-27 15:59:23 2018-04-27 16:15:25          2018-04-27 14:35:00
55b653f93de6e994b6dda90f615c7a8f    delivered      2018-04-30 13:05:23 2018-04-30 13:15:21          2018-04-30 13:01:00
dee6298ce7d1fb2645141ef9972157aa      shipped      2018-04-30 14:06:12 2018-04-30 14:15:24          2018-04-30 12:59:00
51e0e77bc0b6eb43fc25286a873ceac6    delivered      2018-04-30 14:55:34 2018-04-30 16:17:13          2018-04-30 14:41:00
74e033208dc13a7b8127eb8e73d09b76    delivered      2018-05-02 10:48:44 2018-05-02 11:13:45          2018-05-02 09:49:00
2e404f3ac4dd39d7054b4cbb88ce2c35    delivered      2018-05-04 09:49:02 2018-05-04 10:11:27          2018-05-04 09:41:00
d7646ffe8fdd9e7d9557f9f7cbf04530    delivered      2018-05-04 14:50:37 2018-05-04 15:10:22          2018-05-04 14:48:00
7a23cfcc5fcb50ed8cfd257506a5e84b    delivered      2018-05-04 15:07:26 2018-05-04 15:15:23          2018-05-04 13:50:00
978314826289d9ec86d6d6a627eaf810    delivered      2018-05-05 10:58:56 2018-05-05 11:15:10          2018-05-05 09:38:00
71fecd3061e596fd59e65e9d62886535    delivered      2018-05-08 14:17:52 2018-05-08 14:30:18          2018-05-08 13:43:00
6c28cf68e8389e5024135b3d33d8a987    delivered      2018-05-09 12:23:00 2018-05-09 12:35:53          2018-05-09 11:09:00
2ea06e4e577c7be86e2e35ab0d7e74b8    delivered      2018-05-09 13:14:53 2018-05-09 13:35:00          2018-05-09 12:52:00
d454d6650d375ebc3f9667a4d2fe161c    delivered      2018-05-10 09:12:16 2018-05-10 09:35:13          2018-05-10 09:11:00
1227f9af3b2ddb0b95060aab8e5b3dc7    delivered      2018-05-10 14:48:29 2018-05-10 15:11:25          2018-05-10 14:00:00
c3c86ecc0f7508ffce2a4662f49d9d8b    delivered      2018-05-14 12:42:52 2018-05-14 12:55:25          2018-05-14 12:25:00
8299066c13f491b4cf9bdb486d2058c2    delivered      2018-05-14 12:53:23 2018-05-14 13:17:03          2018-05-14 12:43:00

In [36]:
delivery_anomalies = orders[
    orders["order_delivered_customer_date"]
    < orders["order_delivered_carrier_date"]
]

print(
    delivery_anomalies[
        [
            "order_id",
            "order_status",
            "order_purchase_timestamp",
            "order_delivered_carrier_date",
            "order_delivered_customer_date",
            "order_estimated_delivery_date"
        ]
    ].sort_values("order_purchase_timestamp").to_string(index=False)
)

                        order_id order_status order_purchase_timestamp order_delivered_carrier_date order_delivered_customer_date order_estimated_delivery_date
76458889992169d3135b264dc13aec67    delivered      2016-10-07 10:05:16          2016-10-26 11:43:06           2016-10-20 18:03:17                    2016-11-29
f688669f48063536e082bb32d634cd46    delivered      2016-10-07 10:28:56          2016-10-21 18:02:40           2016-10-20 20:33:27                    2016-11-29
19feb5627c41ea1b36a8e50a469b3644    delivered      2016-10-07 17:09:56          2016-10-26 11:42:05           2016-10-20 19:07:54                    2016-12-01
8c78d01de3a9009e23d6877a7cc9be20    delivered      2016-10-08 15:36:50          2016-10-26 11:41:53           2016-10-25 17:51:46                    2016-11-30
b866af202be0692766081310cd4085e1    delivered      2017-01-27 14:59:17          2017-02-20 02:32:08           2017-02-15 03:53:46                    2017-04-17
d5558a097766363b8e76b38c43332e8a    delivered      2017-02-04 19:01:33          2017-02-15 08:55:26           2017-02-10 07:58:32                    2017-03-01
c1e2bf2b7dd3309f2f5356c6b63968fa    delivered      2017-02-10 10:19:10          2017-03-02 17:34:26           2017-02-14 15:15:57                    2017-03-15
771c4f1f521f462e4b95619e648aaeab    delivered      2017-03-22 20:15:15          2017-03-30 13:14:34           2017-03-28 17:28:32                    2017-04-12
29941903985f944b0ffc49c479c1547d    delivered      2017-05-29 16:16:50          2017-06-09 15:07:29           2017-06-02 11:09:16                    2017-06-23
b27af682321527a6349f1761eb3f360c    delivered      2017-06-14 20:17:04          2017-06-27 14:51:54           2017-06-26 15:45:35                    2017-07-14
383aa8b2724fe452d9ccd9934a8c628b    delivered      2017-07-02 20:58:43          2017-07-07 17:22:41           2017-07-06 14:27:51                    2017-07-21
3ee6694bb99d5a6db0deceffcd099597    delivered      2017-07-07 11:22:13          2017-07-11 18:15:40           2017-07-11 17:41:26                    2017-07-20
0922ee1619de7b995648e5a8407afb91    delivered      2017-07-11 10:45:44          2017-07-14 12:41:34           2017-07-12 20:49:42                    2017-08-14
cb1134f9010d242e9515ad1c78ec0c39    delivered      2017-07-16 12:35:34          2017-07-20 19:22:02           2017-07-19 14:13:28                    2017-08-08
5f9d46795c3126674e52becb3a1a517f    delivered      2017-07-18 11:48:20          2017-07-20 23:03:42           2017-07-20 18:52:41                    2017-07-31
ea1dcb4757a844d2642547797bd5feb0    delivered      2017-07-18 13:38:29          2017-07-27 19:21:31           2017-07-25 19:43:10                    2017-08-15
a1abeb653a4d4cd1e142ccb8c82cd069    delivered      2017-07-20 11:20:52          2017-07-28 16:57:58           2017-07-25 19:32:56                    2017-08-14
dceb62e8fa94b46006c9554fed743df0    delivered      2017-07-20 20:58:05          2017-08-01 18:23:30           2017-07-26 18:09:10                    2017-08-11
e37f11cae9985ca58f0b56f268720537    delivered      2017-07-26 11:46:34          2017-08-01 18:17:47           2017-07-31 17:49:56                    2017-08-24
fbffbaaa30f4077e87ec6acdb835b278    delivered      2017-07-30 17:58:26          2017-08-04 20:04:17           2017-08-03 20:30:00                    2017-08-18
fa3e37584f4fdb1ded0e0de700dfcb4e    delivered      2017-07-30 19:32:23          2017-08-09 18:18:43           2017-08-01 21:13:01                    2017-08-18
99ad48402644a3968f2481defdc57947    delivered      2017-08-07 16:36:51          2017-08-12 00:03:35           2017-08-10 21:22:31                    2017-09-05
1cc3ae63caffff2d6c3ee3e78e074acf    delivered      2017-08-07 21:35:22          2017-08-10 18:28:56           2017-08-10 18:05:38                    2017-08-25

In [37]:
print("ORDERS duplicate order_id:", orders["order_id"].duplicated().sum())
print("CUSTOMERS duplicate customer_id:", 
      pd.read_csv("../data/raw/olist_customers_dataset.csv")["customer_id"].duplicated().sum())
print("PRODUCTS duplicate product_id:", 
      products["product_id"].duplicated().sum())
print("SELLERS duplicate seller_id:", 
      pd.read_csv("../data/raw/olist_sellers_dataset.csv")["seller_id"].duplicated().sum())

ORDERS duplicate order_id: 0
CUSTOMERS duplicate customer_id: 0
PRODUCTS duplicate product_id: 0
SELLERS duplicate seller_id: 0

In [38]:
import os
import pandas as pd

# Create cleaned-data folder if it doesn't exist
os.makedirs("../data/cleaned", exist_ok=True)

# Save cleaned geolocation
geo_cleaned.to_csv(
    "../data/cleaned/olist_geolocation_cleaned.csv",
    index=False
)

# Save cleaned orders
orders.to_csv(
    "../data/cleaned/olist_orders_cleaned.csv",
    index=False
)

# Save cleaned order items
items.to_csv(
    "../data/cleaned/olist_order_items_cleaned.csv",
    index=False
)

# Save cleaned reviews
reviews.to_csv(
    "../data/cleaned/olist_order_reviews_cleaned.csv",
    index=False
)

# Save the remaining tables as clean copies
pd.read_csv("../data/raw/olist_customers_dataset.csv").to_csv(
    "../data/cleaned/olist_customers_cleaned.csv",
    index=False
)

payments.to_csv(
    "../data/cleaned/olist_order_payments_cleaned.csv",
    index=False
)

products.to_csv(
    "../data/cleaned/olist_products_cleaned.csv",
    index=False
)

pd.read_csv("../data/raw/olist_sellers_dataset.csv").to_csv(
    "../data/cleaned/olist_sellers_cleaned.csv",
    index=False
)

pd.read_csv("../data/raw/product_category_name_translation.csv").to_csv(
    "../data/cleaned/product_category_name_translation_cleaned.csv",
    index=False
)

print("All cleaned datasets saved successfully.")

All cleaned datasets saved successfully.

In [39]:
import os

print(os.listdir("../data/cleaned"))

['olist_customers_cleaned.csv', 'olist_geolocation_cleaned.csv', 'olist_orders_cleaned.csv', 'olist_order_items_cleaned.csv', 'olist_order_payments_cleaned.csv', 'olist_order_reviews_cleaned.csv', 'olist_products_cleaned.csv', 'olist_sellers_cleaned.csv', 'product_category_name_translation_cleaned.csv']